#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# The MIT License (MIT)
#
# Copyright (c) 2014 Richard Hawkins
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import os

from fuse import FUSE, Operations


class SwiftFusePy(Operations):
    """
    FUSE file system to mount a Swift container.
    """

    def __init__(self, credentials_file, container_name):
        """
        @param credentials_file: absolute path to the file containing the
                                 credentials required to auth with swift.
        @type credentials_file: string
        @param container_name: name of the container to be mounted.
        @type container_name: string
        """
        self.credentials_file = credentials_file
        self.container_name = container_name


def main():
    parser = argparse.ArgumentParser(
        description='Mount a Swift container to your local file system')
    parser.add_argument('--credentials_file', default='~/.swift.creds',
                        help='credentials file for connecting to Swift')
    parser.add_argument('--fsname', default=None, help='file system name')
    parser.add_argument('container_name', help='container to mount')
    parser.add_argument('mount_point',
                        help='directory to mount the container to')

    args = parser.parse_args()
    args.credentials_file = os.path.expanduser(args.credentials_file)

    if not args.fsname:
        args.fsname = 'swift.{0}'.format(args.container_name)

    FUSE(SwiftFusePy(args.credentials_file, args.container_name),
         args.mount_point, foreground=True, fsname=args.fsname)


if __name__ == '__main__':
    main()
